import Foundation

// Start options handed to the PacketTunnelProvider, and the provider
// configuration persisted on NETunnelProviderProtocol.
//
// Option keys follow the sing-box-for-apple convention the provider side
// consumes (Extension/ExtensionProvider.swift resolveStartOptions):
// "configContent" carries the generated sing-box JSON config; the provider
// refuses to start without it. No credentials, node addresses or
// subscription URLs ever appear here — the config content is generated by
// the sakamoto config pipeline, exactly as on macOS (internal/gen).

public struct TunnelStartOptions: Codable, Equatable, Sendable {
    /// The generated sing-box configuration (JSON text). Required.
    public var configContent: String
    /// Optional UI locale forwarded to the core (libbox SetLocale).
    public var locale: String?
    public var profileID: String?
    public var experimentJSON: String?
    public var forceTailscaleDERP: Bool?

    enum CodingKeys: String, CodingKey {
        case configContent
        case locale, profileID, experimentJSON, forceTailscaleDERP
    }

    public init(configContent: String, locale: String? = nil, profileID: String? = nil, experimentJSON: String? = nil, forceTailscaleDERP: Bool? = nil) {
        self.configContent = configContent
        self.locale = locale
        self.profileID = profileID; self.experimentJSON = experimentJSON
        self.forceTailscaleDERP = forceTailscaleDERP
    }

    // MARK: Provider cold/manual start authorization

    public enum ResolutionError: LocalizedError {
        case needsApply, missingConfiguration
        public var errorDescription: String? {
            switch self {
            case .needsApply: return "Open sakamoto and apply the selected configuration before automatic connection."
            case .missingConfiguration: return "Missing or invalid configuration in VPN start options."
            }
        }
    }

    /// Explicit manual starts carry the validated current payload. Unprepared
    /// automatic starts must keep respecting the pending-Apply guard. Never
    /// fall back to an old saved payload when an explicit config is malformed.
    public static func resolveForProvider(startOptions: [String: NSObject]?,
                                          providerConfiguration: [String: Any],
                                          requiresApply: Bool) throws -> Self {
        let explicit = Self(startTunnelOptions: startOptions ?? [:])
        if startOptions?[CodingKeys.configContent.rawValue] != nil,
           explicit?.configContent.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty != false {
            throw ResolutionError.missingConfiguration
        }
        if requiresApply && explicit == nil { throw ResolutionError.needsApply }
        guard let resolved = explicit ?? Self(providerConfiguration: providerConfiguration),
              !resolved.configContent.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw ResolutionError.missingConfiguration
        }
        return resolved
    }

    // MARK: NETunnelProviderProtocol.providerConfiguration

    /// The dictionary stored on NETunnelProviderProtocol.providerConfiguration
    /// so a cold provider launch (device reboot, kill switch re-arm) can
    /// resolve its start options without the app running.
    public var providerConfiguration: [String: Any] {
        var dict: [String: Any] = [CodingKeys.configContent.rawValue: configContent]
        if let locale {
            dict[CodingKeys.locale.rawValue] = locale
        }
        if let profileID { dict[CodingKeys.profileID.rawValue] = profileID }
        if let experimentJSON { dict[CodingKeys.experimentJSON.rawValue] = experimentJSON }
        if let forceTailscaleDERP { dict[CodingKeys.forceTailscaleDERP.rawValue] = forceTailscaleDERP }
        return dict
    }

    /// Recovers the options persisted via `providerConfiguration`. Returns
    /// nil when configContent is missing: the provider must fail loudly at
    /// start rather than guess a configuration.
    public init?(providerConfiguration: [String: Any]) {
        guard let configContent = providerConfiguration[CodingKeys.configContent.rawValue] as? String else {
            return nil
        }
        self.init(
            configContent: configContent,
            locale: providerConfiguration[CodingKeys.locale.rawValue] as? String,
            profileID: providerConfiguration[CodingKeys.profileID.rawValue] as? String,
            experimentJSON: providerConfiguration[CodingKeys.experimentJSON.rawValue] as? String,
            forceTailscaleDERP: providerConfiguration[CodingKeys.forceTailscaleDERP.rawValue] as? Bool
        )
    }

    // MARK: NEVPNConnection.startVPNTunnel(options:)

    /// The per-start options dictionary passed to startVPNTunnel(options:)
    /// (and observed by the provider in startTunnel(options:)).
    public var startTunnelOptions: [String: NSObject] {
        var dict: [String: NSObject] = [
            CodingKeys.configContent.rawValue: configContent as NSString,
        ]
        if let locale {
            dict[CodingKeys.locale.rawValue] = locale as NSString
        }
        if let profileID { dict[CodingKeys.profileID.rawValue] = profileID as NSString }
        if let experimentJSON { dict[CodingKeys.experimentJSON.rawValue] = experimentJSON as NSString }
        if let forceTailscaleDERP { dict[CodingKeys.forceTailscaleDERP.rawValue] = NSNumber(value: forceTailscaleDERP) }
        return dict
    }

    /// Recovers the options received in startTunnel(options:).
    public init?(startTunnelOptions: [String: NSObject]) {
        guard let configContent = startTunnelOptions[CodingKeys.configContent.rawValue] as? String else {
            return nil
        }
        self.init(
            configContent: configContent,
            locale: startTunnelOptions[CodingKeys.locale.rawValue] as? String,
            profileID: startTunnelOptions[CodingKeys.profileID.rawValue] as? String,
            experimentJSON: startTunnelOptions[CodingKeys.experimentJSON.rawValue] as? String,
            forceTailscaleDERP: (startTunnelOptions[CodingKeys.forceTailscaleDERP.rawValue] as? NSNumber)?.boolValue
        )
    }
}
