import Foundation

// Start options handed to the PacketTunnelProvider, and the provider
// configuration persisted on NETunnelProviderProtocol.
//
// Option keys follow the sing-box-for-apple convention the provider side
// consumes (Extension/ExtensionProvider.swift resolveStartOptions):
// "configContent" carries the generated sing-box JSON config; the provider
// refuses to start without it. No credentials, node addresses or
// subscription URLs ever appear here — the config content is generated by
// the sakamoto config pipeline, exactly as on macOS (internal/gen).

public struct TunnelStartOptions: Codable, Equatable, Sendable {
    /// The generated sing-box configuration (JSON text). Required.
    public var configContent: String
    /// Optional UI locale forwarded to the core (libbox SetLocale).
    public var locale: String?

    enum CodingKeys: String, CodingKey {
        case configContent
        case locale
    }

    public init(configContent: String, locale: String? = nil) {
        self.configContent = configContent
        self.locale = locale
    }

    // MARK: NETunnelProviderProtocol.providerConfiguration

    /// The dictionary stored on NETunnelProviderProtocol.providerConfiguration
    /// so a cold provider launch (device reboot, kill switch re-arm) can
    /// resolve its start options without the app running.
    public var providerConfiguration: [String: Any] {
        var dict: [String: Any] = [CodingKeys.configContent.rawValue: configContent]
        if let locale {
            dict[CodingKeys.locale.rawValue] = locale
        }
        return dict
    }

    /// Recovers the options persisted via `providerConfiguration`. Returns
    /// nil when configContent is missing: the provider must fail loudly at
    /// start rather than guess a configuration.
    public init?(providerConfiguration: [String: Any]) {
        guard let configContent = providerConfiguration[CodingKeys.configContent.rawValue] as? String else {
            return nil
        }
        self.init(
            configContent: configContent,
            locale: providerConfiguration[CodingKeys.locale.rawValue] as? String
        )
    }

    // MARK: NEVPNConnection.startVPNTunnel(options:)

    /// The per-start options dictionary passed to startVPNTunnel(options:)
    /// (and observed by the provider in startTunnel(options:)).
    public var startTunnelOptions: [String: NSObject] {
        var dict: [String: NSObject] = [
            CodingKeys.configContent.rawValue: configContent as NSString,
        ]
        if let locale {
            dict[CodingKeys.locale.rawValue] = locale as NSString
        }
        return dict
    }

    /// Recovers the options received in startTunnel(options:).
    public init?(startTunnelOptions: [String: NSObject]) {
        guard let configContent = startTunnelOptions[CodingKeys.configContent.rawValue] as? String else {
            return nil
        }
        self.init(
            configContent: configContent,
            locale: startTunnelOptions[CodingKeys.locale.rawValue] as? String
        )
    }
}
